include:
  - project: 'famedly/company/devops/templates/ci-cd'
    ref: rust-v1
    file:
      - '/rust.yml'

stages:
  - test
  - doc
  - publish

cargo-check:
  extends: .cargo_check

pages:
  extends: .cargo_doc
